/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_simalliance_openmobileapi_service_terminals_ASSDTerminal */

#ifndef _Included_org_simalliance_openmobileapi_service_terminals_ASSDTerminal
#define _Included_org_simalliance_openmobileapi_service_terminals_ASSDTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_simalliance_openmobileapi_service_terminals_ASSDTerminal
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_simalliance_openmobileapi_service_terminals_ASSDTerminal_Close
  (JNIEnv *, jobject);

/*
 * Class:     org_simalliance_openmobileapi_service_terminals_ASSDTerminal
 * Method:    Open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_simalliance_openmobileapi_service_terminals_ASSDTerminal_Open
  (JNIEnv *, jobject);

/*
 * Class:     org_simalliance_openmobileapi_service_terminals_ASSDTerminal
 * Method:    IsPresent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_simalliance_openmobileapi_service_terminals_ASSDTerminal_IsPresent
  (JNIEnv *, jobject);

/*
 * Class:     org_simalliance_openmobileapi_service_terminals_ASSDTerminal
 * Method:    Transmit
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_simalliance_openmobileapi_service_terminals_ASSDTerminal_Transmit
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
